### ISSUE TITLE
Arreglar valores mostrados en el eje y cuando hay pocas mediciones

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/admin-panel#126]
Cuando hay pocas mediciones los límites inferiores y superiores muestran el mismo valor que el de la medición.

**Comment by aibarbetta** [comment]
https://stackoverflow.com/questions/4020796/finding-the-max-value-of-an-attribute-in-an-array-of-objects#4020842
https://formidable.com/open-source/victory/docs/victory-brush-container
https://formidable.com/open-source/victory/docs/victory-chart/#domain
