### ISSUE TITLE
Agregar un error descriptivo cuando se actualiza una configuración avanzada y esta es errónea

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/admin-panel#127]

**Comment by aibarbetta** [comment]
* https://stackoverflow.com/questions/14379274/how-to-iterate-over-a-javascript-object
* https://dmitripavlutin.com/check-if-object-has-property-javascript/
* https://stackoverflow.com/questions/5435228/sort-an-array-with-arrays-in-it-by-string
* https://github.com/hydro-monitor/web-api/pull/94/files
