### ISSUE TITLE
Borrado de una medición y su foto

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/admin-panel#70]

**Comment by aibarbetta** [comment]
https://material-ui.com/components/transfer-list/#enhanced-transfer-
https://codesandbox.io/s/material-demo-5zt8w?file=/demo.js

**Comment by aibarbetta** [comment]
https://material-ui.com/components/transfer-list/#enhanced-transfer-list

**Comment by aibarbetta** [comment]
https://github.com/mui-org/material-ui/issues/8416
